### ISSUE TITLE
Starting debugger on Blender startup

### ISSUE THREAD

**Issue by Andrej730** [hextantstudios/hextant_python_debugger#1]
Any ideas if it's possible to make debugger server to start automatically with Blender? Tried to call operator from startup script but I guess it won't work this way since context is still restricted at startup.

```
Read prefs: "\Blender\4.0\config\userpref.blend"
Traceback (most recent call last):
  File "\Blender\4.0\scripts\modules\bpy\utils\__init__.py", line 131, in _test_import
    mod = __import__(module_name)
  File "\Blender\4.0\scripts\startup\start_debug.py", line 2, in <module>
    bpy.ops.script.start_debug_server()
  File "\Blender\4.0\scripts\modules\bpy\ops.py", line 103, in __call__
    _BPyOpsSubModOp._view_layer_update(context)
  File "\Blender\4.0\scripts\modules\bpy\ops.py", line 66, in _view_layer_update
    view_layer = context.view_layer
AttributeError: '_RestrictContext' object has no attribute 'view_layer'
```

Update. Found a good shortcut to start it at blender startup that's useful during debug: `blender --open-last --python-expr "import bpy; bpy.ops.script.start_debug_server()"`.

**Comment by zaher** [comment]
I added it into my fork , using command line --debug or you can set it by file (Tool->Workspace-<Auto start) when you open the file, I will add PR for it
